import type { Chat, Message, User } from '../types';

export const currentUser: User = {
  id: 'user-0',
  name: 'You',
  status: 'online',
};

export const mockUsers: User[] = [
  {
    id: 'user-1',
    name: 'Sarah Johnson',
    status: 'online',
    lastSeen: 'now',
  },
  {
    id: 'user-2',
    name: 'Michael Chen',
    status: 'online',
    lastSeen: '2 minutes ago',
  },
  {
    id: 'user-3',
    name: 'Emma Williams',
    status: 'away',
    lastSeen: '1 hour ago',
  },
  {
    id: 'user-4',
    name: 'James Rodriguez',
    status: 'offline',
    lastSeen: 'yesterday',
  },
  {
    id: 'user-5',
    name: 'Olivia Martinez',
    status: 'online',
    lastSeen: 'now',
  },
  {
    id: 'user-6',
    name: 'David Kim',
    status: 'offline',
    lastSeen: '3 days ago',
  },
  {
    id: 'user-7',
    name: 'Sophia Anderson',
    status: 'away',
    lastSeen: '30 minutes ago',
  },
  {
    id: 'user-8',
    name: 'Alexander Brown',
    status: 'online',
    lastSeen: 'now',
  },
];

export const mockMessages: Message[] = [
  {
    id: 'msg-1',
    chatId: 'chat-1',
    senderId: 'user-1',
    content: 'Hey! How are you doing?',
    timestamp: new Date(Date.now() - 3600000).toISOString(),
    isRead: true,
  },
  {
    id: 'msg-2',
    chatId: 'chat-1',
    senderId: 'user-0',
    content: "I'm doing great! Just finished working on that new project.",
    timestamp: new Date(Date.now() - 3500000).toISOString(),
    isRead: true,
  },
  {
    id: 'msg-3',
    chatId: 'chat-1',
    senderId: 'user-1',
    content: 'That sounds exciting! How did it turn out?',
    timestamp: new Date(Date.now() - 3400000).toISOString(),
    isRead: true,
  },
  {
    id: 'msg-4',
    chatId: 'chat-1',
    senderId: 'user-0',
    content: 'Really well! The client loved the design and we got approval to move forward.',
    timestamp: new Date(Date.now() - 3300000).toISOString(),
    isRead: true,
  },
  {
    id: 'msg-5',
    chatId: 'chat-1',
    senderId: 'user-1',
    content: "Congratulations! That's amazing news 🎉",
    timestamp: new Date(Date.now() - 1800000).toISOString(),
    isRead: true,
  },
  {
    id: 'msg-6',
    chatId: 'chat-1',
    senderId: 'user-0',
    content: 'Thanks! Want to grab coffee later to celebrate?',
    timestamp: new Date(Date.now() - 600000).toISOString(),
    isRead: true,
  },
  {
    id: 'msg-7',
    chatId: 'chat-1',
    senderId: 'user-1',
    content: "Absolutely! I'm free after 5pm. How about that new cafe downtown?",
    timestamp: new Date(Date.now() - 300000).toISOString(),
    isRead: false,
  },
  {
    id: 'msg-8',
    chatId: 'chat-2',
    senderId: 'user-2',
    content: 'Did you see the latest updates to the project?',
    timestamp: new Date(Date.now() - 7200000).toISOString(),
    isRead: true,
  },
  {
    id: 'msg-9',
    chatId: 'chat-2',
    senderId: 'user-0',
    content: 'Yes! The new features look great.',
    timestamp: new Date(Date.now() - 7000000).toISOString(),
    isRead: true,
  },
  {
    id: 'msg-10',
    chatId: 'chat-2',
    senderId: 'user-2',
    content: "I agree. Let's discuss the implementation details tomorrow.",
    timestamp: new Date(Date.now() - 900000).toISOString(),
    isRead: false,
  },
  {
    id: 'msg-11',
    chatId: 'chat-3',
    senderId: 'user-3',
    content: 'Quick question about the design mockups',
    timestamp: new Date(Date.now() - 14400000).toISOString(),
    isRead: true,
  },
  {
    id: 'msg-12',
    chatId: 'chat-3',
    senderId: 'user-0',
    content: 'Sure, what do you need?',
    timestamp: new Date(Date.now() - 14200000).toISOString(),
    isRead: true,
  },
  {
    id: 'msg-13',
    chatId: 'chat-3',
    senderId: 'user-3',
    content: 'Could you send me the latest version? I need to review the color palette.',
    timestamp: new Date(Date.now() - 10800000).toISOString(),
    isRead: true,
  },
  {
    id: 'msg-14',
    chatId: 'chat-5',
    senderId: 'user-5',
    content: 'Thanks for your help earlier!',
    timestamp: new Date(Date.now() - 21600000).toISOString(),
    isRead: true,
  },
  {
    id: 'msg-15',
    chatId: 'chat-5',
    senderId: 'user-0',
    content: 'No problem! Happy to help anytime.',
    timestamp: new Date(Date.now() - 5400000).toISOString(),
    isRead: true,
  },
];

export const mockChats: Chat[] = [
  {
    id: 'chat-1',
    user: mockUsers[0],
    lastMessage: mockMessages.find((m) => m.chatId === 'chat-1' && m.id === 'msg-7'),
    unreadCount: 1,
    isPinned: true,
    isMuted: false,
    type: 'private',
  },
  {
    id: 'chat-2',
    user: mockUsers[1],
    lastMessage: mockMessages.find((m) => m.chatId === 'chat-2' && m.id === 'msg-10'),
    unreadCount: 1,
    isPinned: false,
    isMuted: false,
    type: 'private',
  },
  {
    id: 'chat-3',
    user: mockUsers[2],
    lastMessage: mockMessages.find((m) => m.chatId === 'chat-3' && m.id === 'msg-13'),
    unreadCount: 0,
    isPinned: false,
    isMuted: false,
    type: 'private',
  },
  {
    id: 'chat-4',
    user: mockUsers[3],
    lastMessage: undefined,
    unreadCount: 0,
    isPinned: false,
    isMuted: true,
    type: 'private',
  },
  {
    id: 'chat-5',
    user: mockUsers[4],
    lastMessage: mockMessages.find((m) => m.chatId === 'chat-5' && m.id === 'msg-15'),
    unreadCount: 0,
    isPinned: true,
    isMuted: false,
    type: 'private',
  },
  {
    id: 'chat-6',
    user: mockUsers[5],
    lastMessage: undefined,
    unreadCount: 0,
    isPinned: false,
    isMuted: false,
    type: 'private',
  },
  {
    id: 'chat-7',
    user: mockUsers[6],
    lastMessage: undefined,
    unreadCount: 0,
    isPinned: false,
    isMuted: false,
    type: 'private',
  },
  {
    id: 'chat-8',
    user: mockUsers[7],
    lastMessage: undefined,
    unreadCount: 0,
    isPinned: false,
    isMuted: false,
    type: 'private',
  },
];
